version: '3.3'
services:
  web:
    image: thejoeejoee/thesaurus-django:${IMAGE_VERSION:-dev}
    command: runserver_prod
    env_file:
      - django/.env.prod

  webpack:
    image: thejoeejoee/thesaurus-webpack:${IMAGE_VERSION:-dev}
    command: build
    environment:
      - NODE_ENV=production
      - PUBLIC_PATH=/static/

  webserver:
    image: thejoeejoee/thesaurus-nginx:${IMAGE_VERSION:-dev}
