version: '3.3'
services:
  web:
    command: runserver_prod
    env_file:
      - django/.env.prod

  webpack:
    command: build
    environment:
      - NODE_ENV=production
      - PUBLIC_PATH=/static/

  db:
    ports:
      - 0.0.0.0:15432:5432