version: '2.2'
services:
  web:
    command: runserver_prod
    env_file:
      - django/.env.prod

  webpack:
    command: build
    environment:
      - NODE_ENV=production
      - PUBLIC_PATH=/static/