version: '2.2'
services:
  web:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=thesaurus
      - POSTGRES_PASSWORD=thesaurus
      - POSTGRES_DB=thesaurus
    healthcheck:
      test: "exit 0"

volumes:
  postgres_data: