version: '2.2'
services:
  web:
    # TODO: think about uvicorn or https://github.com/tiangolo/uvicorn-gunicorn-docker
    # TODO: or just use $ gunicorn -k uvicorn.workers.UvicornWorker
    command: runserver_prod
    env_file:
      - ./web/.env.prod
    depends_on:
      - webpack

  webpack:
    command: build
    environment:
      - NODE_ENV=production
      - PUBLIC_PATH=/static/