version: '2.2'
services:
  web:
    # TODO: think about uvicorn or https://github.com/tiangolo/uvicorn-gunicorn-docker
    # TODO: or just use $ gunicorn -k uvicorn.workers.UvicornWorker
    command: gunicorn thesaurus.wsgi -b 0.0.0.0:8000
    env_file:
      - ./web/.env.prod

  webpack:
    command: build
    environment:
      - NODE_ENV=production
      - PUBLIC_PATH=/static/